### ISSUE TITLE
Error on cdk bootstrap

### ISSUE THREAD

**Issue by cytsen** [aws-samples/amazon-cloudwatch-alarms-repeated-notification-cdk#4]
hi there,
I encounter the below error when running 'cdk bootstrap', does anyone having the same issue?

/amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/typescript/lib/typescript.js:42537
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/typescript/lib/typescript.js:42537:18)
    at /amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/ts-node/src/index.ts:623:55
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/ts-node/src/index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/typescript/lib/typescript.js:116674:163)
    at resolveTypeReferenceDirectiveNamesWorker (/amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/typescript/lib/typescript.js:116974:26)
    at processTypeReferenceDirectives (/amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/typescript/lib/typescript.js:118456:31)
    at findSourceFileWorker (/amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/typescript/lib/typescript.js:118341:21)
    at findSourceFile (/amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/typescript/lib/typescript.js:118196:26)
    at /amazon-cloudwatch-alarms-repeated-notification-cdk/node_modules/typescript/lib/typescript.js:118148:85

Subprocess exited with error 1

Thanks.
Warm Regards

**Comment by weijing24** [comment]
same error

**Comment by weijing24** [comment]
I fix this issue by update this in package.json
```
    "ts-node": "^10.7.0",
    "typescript": "^4.6.4"
```

@dongjaws If possible, please review it https://github.com/aws-samples/amazon-cloudwatch-alarms-repeated-notification-cdk/pull/6
