### ISSUE TITLE
We are not able to do Deploy getting Unable to resolve Aws account Error 

### ISSUE THREAD

**Issue by vignesh-githunt** [aws-samples/amazon-cloudwatch-alarms-repeated-notification-cdk#8]
Hi Team,

  While running Step : cdk deploy --parameters RepeatedNotificationPeriod=3600 --parameters TagForRepeatedNotification=RepeatedAlarm:true --parameters RequireResourceGroup=false

Getting Erro like below:
❌ Deployment failed: Error: Stack Deployments Failed: Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
    at deployStacks (/home/ec2-user/.nvm/versions/node/v16.20.0/lib/node_modules/cdk/node_modules/aws-cdk/lib/index.js:400:129083)
    at async CdkToolkit.deploy (/home/ec2-user/.nvm/versions/node/v16.20.0/lib/node_modules/cdk/node_modules/aws-cdk/lib/index.js:400:147788)
    at async exec4 (/home/ec2-user/.nvm/versions/node/v16.20.0/lib/node_modules/cdk/node_modules/aws-cdk/lib/index.js:455:51984)

Stack Deployments Failed: Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment

Can you please help on this..

**Comment by vignesh-githunt** [comment]
Hi Team,

 Before running cdk bootstrap command getting below Error failed to create CDK toolkit in backend cloudformation.

 Error:
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment

 Please help on this
